language:
  - c
  - c++

compiler:
  - clang
  - gcc

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install cmake

script:
  - mkdir build
  - cd build
  - cmake -DUSE_INTERNAL_GLEW=TRUE -DUSE_INTERNAL_WEBP=TRUE ..
  - cmake --build . --target install
